name: Send Email Every 2 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # svaka 2 minuta
  workflow_dispatch:       # dozvoljava ručno pokretanje

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run email sender
        run: dotnet run --configuration Release --project ./SendEmailApp.csproj
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP: ${{ secrets.EMAIL_SMTP }}

