name: Send Email Every Monday

on:
  schedule:
    - cron: '0 8 * * 5' 
  workflow_dispatch:      

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Spoji PDF chunkove u jedan base64 fajl
        run: |
          mkdir -p Attachments
          printf -n "${PART_1}" > Attachments/pdf.b64
          printf -n "${PART_2}" >> Attachments/pdf.b64
          printf -n "${PART_3}" >> Attachments/pdf.b64
          printf -n "${PART_4}" >> Attachments/pdf.b64

      - name: Dekodiraj PDF
        run: |
          base64 -d Attachments/pdf.b64 > Attachments/saobracajna.pdf

      - name: Run email sender
        run: dotnet run --configuration Release --project ./KPEmailSender.csproj
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

