name: Send Email Every Monday

on:
  schedule:
    - cron: '0 8 * * 5' 
  workflow_dispatch:      

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Create file from BASE64 string
        run: |
          mkdir -p Attachments
          echo "${{ secrets.PDF_PART_1 }}${{ secrets.PDF_PART_2 }}${{ secrets.PDF_PART_3 }}${{ secrets.PDF_PART_4 }}" | base64 --decode > Attachments/saobracajna.pdf
      
      - name: Run email sender
        run: dotnet run --configuration Release --project ./KPEmailSender.csproj
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

